# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token b93138b6f50b29e50d1ef6fc880a3f565f6c69b2

{
  "title": "Шкаф Mouser",
  "description": "ДОРОГО!!! СРОЧНО!!!!"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/17/
Content-Type: application/json
Authorization: Token b93138b6f50b29e50d1ef6fc880a3f565f6c69b2

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

DELETE {{baseUrl}}/advertisements/11/
Content-Type: application/json
Authorization: Token b93138b6f50b29e50d1ef6fc880a3f565f6c69b2
