# Generated by Django 5.0.7 on 2024-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=2, help_text='Введите значение температуры в градусах по Цельсию', max_digits=5),
        ),
    ]
